-- =============================================================================
-- AuditService: Resolution event INSERT into profile_match_log
--
-- Records every getMatchingEntity call for auditability and replay.
-- Fire-and-forget — AuditService.log() never awaits this on the hot path.
-- All v2 columns are populated; v1 columns (match_score, match_type,
-- input_fields) are intentionally omitted for new writes.
--
-- Called by: AuditService.doLog() in audit/audit.service.ts
--
-- Parameters (named — bound by Node.js snowflake-sdk):
--   :log_id                 VARCHAR(36)    UUID generated by Node.js
--   :profile_id             VARCHAR(36)
--   :profile_slug           VARCHAR(100)
--   :source_system          VARCHAR(20)    'Salesforce' | 'Gen3' | 'AdminUI'
--   :correlation_id         VARCHAR(200)   from caller (optional)
--   :input_hash             VARCHAR(64)    SHA2_HEX of sorted input fields
--   :request_payload        VARCHAR        JSON.stringify of full request (cast to VARIANT)
--   :salesforce_id          VARCHAR(50)    null for NO_MATCH
--   :matched_entity_id      VARCHAR(36)    internal entity_id, null for NO_MATCH
--   :confidence_score       NUMBER(5,4)    0.0–1.0
--   :resolution_scenario    VARCHAR(30)    EXACT_MATCH | HIGH_CONFIDENCE | LOW_CONFIDENCE | NO_MATCH
--   :field_scores           VARCHAR        JSON.stringify of field score array (cast to VARIANT)
--   :candidate_count        INTEGER        number of candidates returned (non-zero for LOW_CONFIDENCE)
--   :threshold_used         NUMBER(5,4)    profile default_threshold or request override
--   :was_cached             BOOLEAN
--   :execution_ms           INTEGER
--   :model_version          VARCHAR(50)    e.g. 'e5-base-v2'
--   :profile_snapshot_ts    TIMESTAMP_NTZ  timestamp of profile config used
--   :entities_snapshot_ts   TIMESTAMP_NTZ  timestamp of last entity sync at resolution time
--   :error_code             VARCHAR(50)    null on success
--   :error_message          VARCHAR(2000)  null on success
-- =============================================================================

INSERT INTO profile_match_log (
    log_id,
    profile_id,
    profile_slug,
    source_system,
    correlation_id,
    input_hash,
    request_payload,
    salesforce_id,
    matched_entity_id,
    confidence_score,
    resolution_scenario,
    field_scores,
    candidate_count,
    threshold_used,
    was_cached,
    execution_ms,
    model_version,
    profile_snapshot_ts,
    entities_snapshot_ts,
    error_code,
    error_message,
    created_at
)
VALUES (
    :log_id,
    :profile_id,
    :profile_slug,
    :source_system,
    :correlation_id,
    :input_hash,
    PARSE_JSON(:request_payload),
    :salesforce_id,
    :matched_entity_id,
    :confidence_score,
    :resolution_scenario,
    PARSE_JSON(:field_scores),
    :candidate_count,
    :threshold_used,
    :was_cached,
    :execution_ms,
    :model_version,
    :profile_snapshot_ts::TIMESTAMP_NTZ,
    :entities_snapshot_ts::TIMESTAMP_NTZ,
    :error_code,
    :error_message,
    CURRENT_TIMESTAMP()
);
