/**
 * Domain models for entities and embeddings.
 * Entities are the records stored in a profile that incoming requests match against.
 */

/**
 * A stored entity within a resolution profile.
 * Field values are stored as a flexible key-value map (Snowflake VARIANT column).
 */
export interface Entity {
  readonly entityId: string;
  readonly profileId: string;
  /** Primary display label derived from the isPrimaryDisplay field. */
  readonly displayName: string;
  /** All field values for this entity: { "name": "Acme Corp", "tax_id": "36-..." } */
  readonly fieldValues: Readonly<Record<string, string>>;
  readonly isActive: boolean;
  /** ID in the external system (e.g., Salesforce Account ID). */
  readonly externalId?: string;
  /** Source system that owns this entity (e.g., "Salesforce"). */
  readonly sourceSystem?: string;
  /** Optimistic concurrency version counter. */
  readonly version: number;
  readonly createdAt: Date;
  readonly updatedAt: Date;
  /** Optional ANN search metadata (field name -> similarity score) for optimization. */
  _scoringMetadata?: Record<string, number>;
}

/**
 * A vector embedding for a single field of an entity.
 * Generated by Snowflake Cortex EMBED_TEXT_768 ('e5-base-v2').
 */
export interface EntityEmbedding {
  readonly entityId: string;
  readonly profileId: string;
  readonly fieldName: string;
  /** The original text that was embedded (for cache invalidation and audit). */
  readonly sourceText: string;
  /** 768-dimensional dense vector from e5-base-v2. */
  readonly embedding: Float32Array;
  readonly modelVersion: string;
  readonly generatedAt: Date;
}

/** Input for creating or upserting an entity. */
export interface UpsertEntityInput {
  readonly profileId: string;
  readonly displayName: string;
  readonly fieldValues: Record<string, string>;
  readonly externalId?: string;
  readonly sourceSystem?: string;
  readonly metadata?: Record<string, unknown>;
}

/** Input for bulk-loading many entities at once. */
export interface BulkEntityInput {
  readonly displayName?: string;
  readonly fields: Record<string, string>;
  readonly externalId?: string;
  readonly metadata?: Record<string, unknown>;
}

/** Result of a bulk load operation. */
export interface BulkLoadResult {
  readonly totalLoaded: number;
  readonly embeddingsGenerated: number;
  readonly executionMs: number;
}
