import type { IMatchStrategy, StrategyContext } from '../common/ports/match-strategy.port';
import type { MatchStrategy } from '../common/models/profile.model';

/**
 * SEMANTIC matching strategy.
 *
 * Computes cosine similarity between two pre-fetched embedding vectors.
 * The embeddings are generated by Snowflake Cortex EMBED_TEXT_768 ('e5-base-v2')
 * and must be passed in via `context.inputEmbedding` and `context.candidateEmbedding`.
 *
 * The cosine similarity math runs entirely in Node.js (NOT in Snowflake SQL).
 * V8 JIT makes this ~6x faster than pure CPython for 768-dim vectors.
 *
 * Suitable for: company names, product descriptions, addresses — any field
 * where semantic meaning matters more than character-level similarity.
 *
 * NOTE: This strategy requires embeddings to be pre-fetched by EmbeddingFetcher
 * before score() is called. If embeddings are missing, returns 0.0.
 */
export class SemanticStrategy implements IMatchStrategy {
  readonly strategyName: MatchStrategy = 'SEMANTIC';

  /**
   * Computes cosine similarity between pre-fetched embedding vectors.
   * If precomputed similarity from ANN search is available in context, uses that instead.
   * @param _input - Not used directly (embedding in context).
   * @param _candidate - Not used directly (embedding in context).
   * @param context - Must contain inputEmbedding + candidateEmbedding OR precomputedSimilarity.
   * @returns Cosine similarity score in [0.0, 1.0].
   */
  score(
    _input: string,
    _candidate: string,
    context?: StrategyContext,
  ): number {
    // Use pre-computed similarity from ANN search if available (avoids redundant calculation)
    if (context?.precomputedSimilarity !== undefined) {
      return context.precomputedSimilarity;
    }

    if (!context?.inputEmbedding || !context?.candidateEmbedding) {
      return 0.0;
    }

    return this.cosineSimilarity(
      context.inputEmbedding,
      context.candidateEmbedding,
    );
  }

  /**
   * Computes cosine similarity between two Float32Arrays.
   * Formula: dot(a, b) / (||a|| * ||b||)
   * @param a - First embedding vector (768-dim).
   * @param b - Second embedding vector (768-dim).
   * @returns Similarity score clamped to [0.0, 1.0].
   */
  private cosineSimilarity(a: Float32Array, b: Float32Array): number {
    let dotProduct = 0;
    let normA = 0;
    let normB = 0;

    for (let i = 0; i < a.length; i++) {
      dotProduct += a[i] * b[i];
      normA += a[i] ** 2;
      normB += b[i] ** 2;
    }

    const denominator = Math.sqrt(normA) * Math.sqrt(normB);

    if (denominator === 0) {
      return 0.0;
    }

    return Math.max(0, Math.min(1, dotProduct / denominator));
  }

  /**
   * Normalize text by trimming and lowercasing for case-insensitive semantic matching.
   * This must match the normalization applied before embedding generation.
   */
  normalize(value: string): string {
    return value.trim().toLowerCase();
  }

  /** SEMANTIC strategy requires pre-fetched embeddings in context. */
  requiresEmbedding(): boolean {
    return true;
  }

  /** SEMANTIC strategy's score() is synchronous (embeddings pre-fetched). */
  isAsync(): boolean {
    return false;
  }
}
